# Starts a bitcoind node and an electrs node in regtest
services:
  bitcoind:
    build: bitcoind
    ports:
      - 18443:18443

  electrs:
    build: electrs
    command: --daemon-rpc-addr=bitcoind:18443
      --daemon-dir=/var/lib/bitcoin/
    volumes_from:
      - bitcoind:ro
