services:
  electrs:
    extends:
      file: docker-compose-nodes.yml
      service: electrs
    ports:
      - 60401:60401
      - 9000:9000

  bitcoind:
    extends:
      file: docker-compose-nodes.yml
      service: bitcoind
    volumes:
      - ./wallets:/var/lib/bitcoin/regtest/wallets

  mempool-frontend:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "mempool-backend"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 5000:8080
    depends_on:
      - mempool-db

  mempool-backend:
    environment:
      MEMPOOL_BACKEND: "electrum"
      CORE_RPC_HOST: "bitcoind"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "bitcoin"
      CORE_RPC_PASSWORD: "local123"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "60401"
      ELECTRUM_TLS_ENABLED: "false"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
    depends_on:
      - mempool-db
      - electrs
    volumes:
      - ./data:/backend/cache

  mempool-db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
